Pokedex app
jorge-prieto/pokedex-redux pull request #1
Opened 2021-08-10 05:05 UTC by jorge-prieto

2021-08-10 22:00 UTC, hackeo1 requested changes
- naming convention for the assets must be consistent
- review the consistency between single a double quotes, when one is used and when the other

2021-08-10 22:00 UTC, hackeo1 commented on package.json
> +    "yarn": "^1.22.11"
don't add yarn as a dependency

2021-08-10 22:00 UTC, hackeo1 commented on public/index.html
> +    <title>React App</title>
change the title

2021-08-10 22:00 UTC, hackeo1 commented on src/components/Card.js
> +  const image = 'https://raw.githubusercontent.com/PokeAPI/sprites/146c91287ad01f6e15315bbd733fd7442c91fe6d/sprites/pokemon/' + getIdFromPokenUrl(url) + '.png'
use a central file to manage the base urls

2021-08-10 22:00 UTC, hackeo1 commented on src/components/Card.js
> +    e.preventDefault()
don't use single char variables

2021-08-10 22:00 UTC, hackeo1 commented on src/components/Modal.css
> +  background-color: rgba(0,0,0, 0.3);
use variables for the colors

2021-08-10 22:00 UTC, hackeo1 commented on src/components/Modal.css
> +  background-color: #eee;
use variables for the colors

2021-08-10 22:00 UTC, hackeo1 commented on src/components/Modal.css
> +  box-shadow: 0px 0px 15px gray;
don't use named colors

2021-08-10 22:00 UTC, hackeo1 commented on src/components/Modal.css
> +  background-color: blue;
don't use named colors

2021-08-10 22:00 UTC, hackeo1 commented on src/components/Modal.css
> +  float: left;
don't use float

2021-08-10 22:00 UTC, hackeo1 commented on src/components/Modal.css
> +  background-color: #aaa;
use variables

2021-08-10 22:00 UTC, hackeo1 commented on src/components/Modal.js
> +        <div className="">
remove unused attributes

2021-08-10 22:00 UTC, hackeo1 commented on src/components/Modal.js
> +        <div className="">FOOTER</div>
remove unused attributes

2021-08-10 22:00 UTC, hackeo1 commented on src/components/Modal.js
> +    fetch(url)
fetch should be done using the store

2021-08-10 22:00 UTC, hackeo1 commented on src/components/NavBar.js
> +  function onChange(e) {
don't use single character variables

2021-08-10 22:00 UTC, hackeo1 commented on src/components/NavBar.js
> +          <img src={LOGO} alt='Pokemon logo' className='img-logo' />
keep the consistency, double quotes here?

2021-08-10 22:00 UTC, hackeo1 commented on src/helper/helps.js
> + return 'https://raw.githubusercontent.com/PokeAPI/sprites/146c91287ad01f6e15315bbd733fd7442c91fe6d/sprites/pokemon/' + id + '.png'
keep base urls centralized

2021-08-10 22:00 UTC, hackeo1 commented on src/pages/Home.css
> +}
this file has different indentation

2021-08-10 22:00 UTC, hackeo1 commented on src/pages/PokemonsList.js
> +        data_filtered.map((el, i) => <Card key={i} name={el.name} url={el.url} onClick={onClickPokemons} />)
don't use single character variables

2021-08-13 14:53 UTC, jugonz31 reviewed
- Add React import statement in all components
- please take a look at how you name items, classes, components, and folders in all the project:

> use UpperCamelCase for components (MyComponent.js - export default MyComponent)
> use camelCase for constants, props, variables, etc. (let myVariable = 0; const myConst = true;)
> use snake_case or kebab-case for CSS classes: (.my-class {})
> use kebab-case for folders (src/components/my-component/MyComponent.js)

- Try fixing import order and run a formatter in all your project 
- Use clearer names for everything

2021-08-13 14:53 UTC, jugonz31 commented on src/App.js
> +import { useEffect, useState } from 'react';
Add import for React

```suggestion
import React, { useEffect, useState } from 'react';
```

2021-08-13 14:53 UTC, jugonz31 commented on src/App.js
> +import { Navigator} from './components'
Try formatting the code, you need some extra spaces in all this: 
```suggestion
import { useSelector, useDispatch } from 'react-redux'
import { MProvider } from './store/redux_store'
import {fetchPokemons } from './store/slicePokemons'
import { Navigator } from './components'
```

2021-08-13 14:53 UTC, jugonz31 commented on src/App.js
> +import { Navigator} from './components'
I suggest you to check how to use 'Prettier' in your project, or you can just use the VSCode formatter

2021-08-13 14:53 UTC, jugonz31 commented on src/components/Card.css
> +.card .card-name {
add spaces between class declarations: 
```suggestion
}

.card:hover {
  transform: scale(1.1);
}

.card .card-image {
  display: block;
  width: 90%;
  object-fit: contain;
}

.card .card-name {
```

2021-08-13 14:53 UTC, jugonz31 commented on src/components/Card.js
> +import { images } from '../Services';
Add import statement for React

2021-08-13 14:53 UTC, jugonz31 commented on src/components/Modal.css
> +  --shadow: rgba(0, 0, 0, 0.3);
Would be better to define CSS variables in another place, so you can use them wherever you want and have it more organized

2021-08-13 14:53 UTC, jugonz31 commented on src/components/Modal.js
> +import { fetchPoken, initCompare, clearModal } from '../store/sliceModal';
Import statements must have an order. Like this:
React imports should go first, followed by libraries and external tools (like react-redux in this case), followed by components and utils from your project and CSS files at the end.

There are tools that can do this for you. This is also part of formatting the code.

2021-08-13 14:53 UTC, jugonz31 commented on src/components/Modal.js
> +  const { left, right, is_compared, initialCompare, closeAndClean } = useManager(url, onClose);
always use lowerCamelCase to define constants, avoid using snake_case

2021-08-13 14:53 UTC, jugonz31 commented on src/components/Modal.js
> +function Ul({ data }) {
be careful and try naming functions in a better way 😅

2021-08-13 14:53 UTC, jugonz31 commented on src/components/Modal.js
> +function PokenDescription({id, desc, height, weight, gender, abilities, types}) {
also naming constants or props
```suggestion
function PokenDescription({id, description, height, weight, gender, abilities, types}) {
```

2021-08-13 14:53 UTC, jugonz31 commented on src/components/Modal.js
> +function Compared({ left, right }) {
functions should never start with uppercase. always should be lowerCamelCase

2021-08-13 14:53 UTC, jugonz31 commented on src/components/Modal.js
> +                    right[fields[camp]].map((abilitie, key) => (
fix typo 'abilitie'

2021-08-13 14:53 UTC, jugonz31 commented on src/components/NavBar.js
> +import { appendFilter } from '../store/slicePokemons';
this is also a valid way to order imports, it is acceptable

2021-08-13 14:53 UTC, jugonz31 commented on src/components/index.js
> +export * from './Card'
add eof new line

2021-08-13 14:53 UTC, jugonz31 commented on src/helper/helps.js
> +}
add eof new line

2021-08-13 14:53 UTC, jugonz31 commented on src/pages/PokemonsList.js
> +  const { selected, data_filtered, onClickPokemons, onCloseModal } =
same issue with the snake_case

2021-08-13 14:53 UTC, jugonz31 commented on src/pages/PokemonsList.js
> +  const { selected, data_filtered, onClickPokemons, onCloseModal } =
also fix the typo 'data filtered'

2021-08-13 14:53 UTC, jugonz31 commented on src/pages/PokemonsList.js
> +function useManager() {
try always using arrow functions, it is more common

2021-08-13 14:53 UTC, jugonz31 commented on src/pages/PokemonsList.js
> +  const [selected, setSelect] = useState();
```suggestion
  const [selected, setSelected] = useState();
```

2021-08-13 14:53 UTC, jugonz31 commented on src/pages/PokemonsList.js
> +  const { array, textfilter } = useSelector((state) => state.pokemons);
lowerCamelCase for constants!!!
```suggestion
  const { array, textFilter } = useSelector((state) => state.pokemons);
```

2021-08-13 14:53 UTC, jugonz31 commented on src/pages/index.js
> +export * from './PokemonsList'
eof

2021-08-13 14:53 UTC, jugonz31 commented on src/pages/pokemonsList.css
> +}
eof

2021-08-17 20:10 UTC, jugonz31 approved these changes

2021-08-17 22:03 UTC, hackeo1 requested changes

2021-08-17 22:03 UTC, hackeo1 commented on src/components/Modal.js
> +      <table>
don't use table, use display table instead

2021-08-17 22:03 UTC, hackeo1 commented on src/store/sliceModal.js
> +    isCompared: false,
this file has 4 spaces for indentation instead of 2

2021-08-19 13:22 UTC, hackeo1 approved these changes

2021-08-23 01:01 UTC, merged